name:                hascpvo
version:             0.1.0.0
github:              "githubuser/hascpvo"
license:             BSD3
author:              "Hasan Al Rasyid"
maintainer:          "hasan@compscience.itb.ac.id"
copyright:           "2018 Hasan Al Rasyid"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hascpvo#readme>

dependencies:
- base >= 4.7 && < 5
- text
- pandoc
- process
- hmatrix
- boxes
- foldl
- turtle
- split
- text-format
- inline-c
- vector

library:
  source-dirs: src

executables:
  test:
    #c-sources:           app/test.c
    #cc-options:          -Wall -O2
    #extra-libraries:     -lm
    extra-lib-dirs: foreign/lib
    extra-libraries: test
    main:                test.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hascpvo
    - text-format
    - split
    - text
  
  f1:
    main:                f1PdosTotAtomicMajorOrbitalVert.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hascpvo
    - text-format
    - split
    - text
  
  t1:
    main:                t1dosEf.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hascpvo
    - text-format
    - split
    - text
  
  t2:
    main:                t2DOSintegration.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hascpvo
    - text-format
    - split
    - text

  t3:
    main:                t3atomicMagneticMoment.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hascpvo
    - text-format
    - split
    - text

  x:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hascpvo

tests:
  tf1:
    main:                f1.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hascpvo
    - text-format
    - split
    - text
  hascpvo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hascpvo
    - text-format
    - split
    - text
